version: '3.0'
services:
  client:
    build: ./client
    restart: always
    volumes:
      - "./client:/client"
      - "/client/node_modules"
      - "/client/build"
    ports:
      - "8080:8080"
    command: yarn start:prod -port 8080
  api:
    build: ./api
    restart: always
    volumes:
      - "./api:/api"
      - "/api/node_modules"
    ports:
      - "3000:3000"
    command: npm run start
